### PR TITLE
bandage: Add BLAST

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks for merging, Tiago! Could you please comment here when you've built the Docker image?

**Comment by tiagofilipe12** [comment]
Just one last thing. Which tag would you like to use in docker hub? `0.8.1`, right?

**Comment by tiagofilipe12** [comment]
I have started the build of this image. It is available [here](https://hub.docker.com/r/flowcraft/bandage/). Still building though. Thanks for the contribution 👍 .

**Comment by sjackman** [comment]
Thanks!

**Comment by sjackman** [comment]
The image is still 1.6 GB. It can be made smaller with some more work.

**Pull request merged**
