### PR TITLE
Add bandage

### PR DESCRIPTION
**Pull request by sjackman**
The pull request for the Flowcraft component is coming tomorrow.

### CODE REVIEW

**Comment by sjackman** [comment]
I've update this PR to use the static executable https://github.com/rrwick/Bandage/releases to make a smaller image than using a package manager.

The `quay.io/biocontainers/bandage:0.8.1--hb59a952_0` image unfortunately doesn't work.

```
# Bandage --version
This application failed to start because it could not find or load the Qt platform plugin "minimal"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted
```

The Linuxbrew Docker image after `brew install blast brewsci/bio/bandage` was 3.9 GB!

**Comment by ODiogoSilva** [comment]
Whoa! Ok, this one looks good, I'll have it building shortly. 👍

**Comment by sjackman** [comment]
I forgot BLAST! wait one sec before building the image.

**Comment by sjackman** [comment]
See PR https://github.com/assemblerflow/docker-imgs/pull/5 to add BLAST to this image.

**Pull request merged**
